DELETE http://localhost:3003/api/blogs/60770d6031316f24b88d62b1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJ3aXRoYmxvZ3M0IiwiaWQiOiI2MDc3MDMwYTg2ZWQwZDIyMzIyNDMzZTMiLCJpYXQiOjE2MTg0OTgzMDEsImV4cCI6MTYxODUwMTkwMX0.WPN539rIV3v671GsjPengLad5xO7gTrC5Gn0l3PXBiA